name: Docker build and push (preview)

on:
  push:
    branches:
      - "preview"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Install dependencies
        run: dotnet restore Tests

      - name: Build
        run: dotnet build Tests

      - name: Test with the dotnet CLI
        run: dotnet test Tests

  docker:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kidlatte/destuff:preview
